export enum CognitionEventType {

    MARKET_RECEIVED =
        "MARKET_RECEIVED",

    PERCEPTION_COMPLETED =
        "PERCEPTION_COMPLETED",

    UNDERSTANDING_COMPLETED =
        "UNDERSTANDING_COMPLETED",

    REASONING_COMPLETED =
        "REASONING_COMPLETED",

    ACTION_GENERATED =
        "ACTION_GENERATED",

    GOVERNANCE_COMPLETED =
        "GOVERNANCE_COMPLETED",

    REFLECTION_COMPLETED =
        "REFLECTION_COMPLETED",

    MEMORY_UPDATED =
        "MEMORY_UPDATED"

}